name: Continuous Integration

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover
    - name: Create Test Coverage Badge
      if: github.ref == 'refs/heads/code-coverage-badge'
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Test Coverage
        color: brightgreen
        path: "tests/Elzik.Mecon.Framework.Tests.Unit/TestResults/coverage.opencover.xml"
        gist-filename: code-coverage.json
        gist-id: 527882e89a938dc78f61a08c300edec4
        gist-auth-token: ${{ secrets.CODE_COVERAGE_AUTH_TOKEN }}  
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"